export const THEMES = {
  clean: {
    lightSquare:       '#f0f0f0',
    darkSquare:        '#6a9fb5',
    highlight:         '#fff59d',
    selectedHighlight: '#ffce20cc',
    lastMove:          '#f0c800cc',
    background:  '#f0f0f0',
    text:        '#1a1a1a',
    panelBg:     '#f8f8f8',
    border:      '#aaaaaa',
    buttonBg:    '#e2e8f0',
    buttonText:  '#1a202c',
    activeButton:'#3b82f6',
  },
  wood: {
    lightSquare:       '#ffce9e',
    darkSquare:        '#d18b47',
    highlight:         '#c8dc7acc',
    selectedHighlight: '#5e8e20cc',
    lastMove:          '#799e3acc',
    background:  '#2d4a35',
    text:        '#f5e6d3',
    panelBg:     '#243d2c',
    border:      '#4a7060',
    buttonBg:    '#2d5a3a',
    buttonText:  '#f5e6d3',
    activeButton:'#c0833a',
  },
  starwars: {
    lightSquare:       '#1e3a5f',
    darkSquare:        '#060a18',
    highlight:         '#00d4ff',
    selectedHighlight: '#0099bb',
    lastMove:          '#ff4500',
    background:  '#05050f',
    text:        '#c8d6e5',
    panelBg:     '#0a0a1f',
    border:      '#1e3a5f',
    buttonBg:    '#0f1f3d',
    buttonText:  '#8ab4d4',
    activeButton:'#e8242c',
  },
};
